spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3399/CitaTeBBDD
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver
  sql:
    init:
      mode: always
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop
      show-sql: false
      hibernate:
        format-sql: true
server:
   port: 8093